name: user_repository
description: Dart package which manages the user.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

  # Firebase
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.1.0
  firebase_core: ^2.9.0
  flutter_login_facebook: ^2.0.0
  google_sign_in: ^6.2.1
  firebase_database: ^10.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true